services:
  nginx:
    image: nginx:stub_status
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - ./nginx/nginx_sites_available:/etc/nginx/sites-available/default:ro
      - nginx_logs:/var/log/nginx
    networks:
      - monitoring_prod
    restart: always

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
    networks:
      - monitoring_dev
    restart: always

  nginx_prometheus_exporter:
    image: nginx/nginx-prometheus-exporter:1.2.0
    container_name: nginx_prometheus_exporter
    command: ["--nginx.scrape-uri", "http://nginx/nginx_status"]
    networks:
      - monitoring_prod
    restart: always

  telegraf:
    image: telegraf:1.29.5
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - nginx_logs:/var/log/nginx:ro
    networks:
      - monitoring_prod
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - monitoring_prod
    restart: always

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring_prod
    restart: always

  grafana:
    image: grafana/grafana:10.3.3
    container_name: grafana
    ports:
      - 3456:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring_prod
    restart: always

volumes:
  nginx_logs:
  grafana_data:
  prometheus_data:

networks:
  monitoring_prod:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
