global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx_prometheus_exporter:9113"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
